name: Publish Snapshot to GitHub Packages
on:
  workflow_run:
    workflows: ["Gradle Build"]
    branches: [main]
    types: [completed]
jobs:
  publish-to-github-packages:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish Snapshot to GitHub Packages
        run: ./gradlew -Pgithub-packages publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
